---
clusterName: play-ops
talosVersion: v1.9.2
kubernetesVersion: v1.32.0
endpoint: https://play.impl.nl:6443
allowSchedulingOnMasters: true
additionalMachineCertSans:
  - play.impl.nl
  - 192.168.1.97
additionalApiServerCertSans:
  - play.impl.nl
  - 192.168.1.97
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12

nodes:
  - hostname: node97
    ipAddress: 192.168.1.97
    controlPlane: true
    installDisk: /dev/mmcblk0
    patches:
      - |-
        - op: add
          path: /machine/network/interfaces
          value:
            - interface: end0
              addresses:
                - 192.168.1.97/24
                - 10.245.1.1/15
              routes:
                - network: 0.0.0.0/0
                  gateway: 192.168.1.1
              dhcp: false
  - hostname: node98
    ipAddress: 192.168.1.98
    controlPlane: true
    installDisk: /dev/mmcblk0
    patches:
      - |-
        - op: add
          path: /machine/network/interfaces
          value:
            - interface: end0
              addresses:
                - 192.168.1.98/24
                - 10.245.1.2/15
              routes:
                - network: 0.0.0.0/0
                  gateway: 192.168.1.1
              dhcp: false
  - hostname: node99
    ipAddress: 192.168.1.99
    controlPlane: true
    installDisk: /dev/mmcblk0
    patches:
      - |-
        - op: add
          path: /machine/network/interfaces
          value:
            - interface: end0
              addresses:
                - 192.168.1.99/24
                - 10.245.1.3/15
              routes:
                - network: 0.0.0.0/0
                  gateway: 192.168.1.1
              dhcp: false
  - hostname: node100
    ipAddress: 192.168.1.100
    controlPlane: false
    installDisk: /dev/mmcblk0
    patches:
      - |-
        - op: add
          path: /machine/network/interfaces
          value:
            - interface: end0
              addresses:
                - 192.168.1.100/24
                - 10.245.1.4/15
              routes:
                - network: 0.0.0.0/0
                  gateway: 192.168.1.1
              dhcp: false
  - hostname: node101
    ipAddress: 192.168.1.101
    controlPlane: false
    installDisk: /dev/mmcblk0
    patches:
      - |-
        - op: add
          path: /machine/network/interfaces
          value:
            - interface: end0
              addresses:
                - 192.168.1.101/24
                - 10.245.1.5/15
              routes:
                - network: 0.0.0.0/0
                  gateway: 192.168.1.1
              dhcp: false
  - hostname: node102
    ipAddress: 192.168.1.102
    controlPlane: false
    installDisk: /dev/mmcblk0
    patches:
      - |-
        - op: add
          path: /machine/network/interfaces
          value:
            - interface: end0
              addresses:
                - 192.168.1.102/24
                - 10.245.1.6/15
              routes:
                - network: 0.0.0.0/0
                  gateway: 192.168.1.1
              dhcp: false
