repo:
  url: https://github.com/bhuism/play-ops.git
  revision: main

applications:
  - name: echo
    app-namespace: argocd
    namespace: echo
    path: main/echo
    manifest-paths: /main/echo
    syncOptions:
      - CreateNamespace=true
    # helm:
    #   enabled: true
