echo:
  ingress:
    enabled: true
    ingressClassName: nginx
    pathType: Prefix
    extraPaths: []
    hosts:
      - host: echo.play.impl.nl
        paths:
          - /
  application:
    enable:
      environment: false
