echo:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      external-dns.alpha.kubernetes.io/target: jasmine.odee.net
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      cert-manager.io/cluster-issuer: letsencrypt-production
      gethomepage.dev/enabled: "true"
    pathType: Prefix
    extraPaths: []
    hosts:
      - host: echo.impl.nl
        paths:
          - /
    tls:
      - secretName: echo.impl.nl
        hosts:
          - echo.impl.nl
  application:
    enable:
      environment: false
