argo-cd:
  dex:
    enabled: false
  repoServer:
    env:
      - name: ARGOCD_EXEC_TIMEOUT
        value: 300s
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false

  configs:
    cm:
      admin.enabled: true
      application.resourceTrackingMethod: annotation+label
      url: https://argocd.play.impl.nl
    rbac:
      policy.default: role:admin
    params:
      server.insecure: true
    repositories:
      helm:
        type: helm
        url: https://charts.helm.sh/stable
      argo:
        type: helm
        url: https://argoproj.github.io/argo-helm
      playops:
        type: git
        url: https://github.com/bhuism/play-ops.git

  server:
    redis:
      metrics:
        enabled: false
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: argocd.play.impl.nl
    extraArgs:
      - --insecure
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false


  controller:
    replicas: 1
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
    args:
      repoServerTimeoutSeconds: 300
