repo:
  url: https://github.com/bhuism/play-ops.git
  revision: main

applications:
  - name: argocd
    app-namespace: argocd
    namespace: argocd
    path: argocd
    manifest-paths: /argocd
    sync-wave: "-5"

  - name: infrastructure
    namespace: argocd
    path: infrastructure/
    manifest-paths: /infrastructure
    sync-wave: "-4"

  - name: main
    namespace: argocd
    path: main/
    sync-wave: "-3"

  - name: root
    app-namespace: argocd
    namespace: argocd
    path: root
    manifest-paths: /root

