repo:
  url: https://github.com/bhuism/play-ops.git
  revision: main

applications:
  - name: cilium
    app-namespace: argocd
    namespace: kube-system
    path: infrastructure/cilium
    manifest-paths: /infrastructure/cilium
    sync-wave: "-5"
    helm:
      enabled: true
  - name: ingress-nginx
    app-namespace: argocd
    namespace: ingress-nginx
    path: infrastructure/ingress-nginx
    manifest-paths: /infrastructure/ingress-nginx
    sync-wave: "-4"
    helm:
      enabled: true
    syncOptions:
      - CreateNamespace=true
